URLs:
    GRCh38:
        gtf: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v43.basic.annotation.gtf.gz"
        genome: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.primary_assembly.genome.fa.gz"
        cdna: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.pc_transcripts.fa.gz"
    GRCm39:
        gtf: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/gencode.vM33.basic.annotation.gtf.gz"
        genome: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/GRCm39.primary_assembly.genome.fa.gz"
        cdna: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/gencode.vM33.pc_transcripts.fa.gz"

outfold_genome: "resources/genome"
outfold_fastq: "resources/fastq"

outfold_star: "results/star"
outfold_counts: "results/counts"
outfold_norm: "results/norm_counts"
outfold_binned: "results/binned_norm_counts"
outfold_fig: "results/fig"
outfold_phase_amp: "results/phase_amp"
outfold_space_time_fourier: "results/space_time_fourier"
outfold_kalman: "results/kalman"

Species: GRCm39
read_length: 75
adapter: TGGAATTCTCGGGTGCCAAGG
Bin_size:
    #- '100'
    #- '200'
    #- '300'
    #- '500'
    - '1000'
    #- '10000'
Samples:
    - PRO_SEQ_CT00_S1_R1_001
    - PRO_SEQ_CT04_S2_R1_001
    - PRO_SEQ_CT08_S3_R1_001
    - PRO_SEQ_CT12_S4_R1_001
    - PRO_SEQ_CT16_S5_R1_001
    - PRO_SEQ_CT20_S6_R1_001
    - PRO_SEQ_CT24_S7_R1_001
    - PRO_SEQ_CT28_S8_R1_001
    - PRO_SEQ_CT32_S9_R1_001
    - PRO_SEQ_CT36_S10_R1_001
    - PRO_SEQ_CT40_S11_R1_001
    - PRO_SEQ_CT44_S12_R1_001
Strands:
    - forward
    - reverse
Chromosomes:
    Test:
        - chr17
    GRCm39:
        - chr1
        - chr2
        - chr3
        - chr4
        - chr5
        - chr6
        - chr7
        - chr8
        - chr9
        - chr10
        - chr11
        - chr12
        - chr13
        - chr14
        - chr15
        - chr16
        - chr17
        - chr18
        - chr19
        - chrX
        - chrY
        - chrM

Space_Time_Fourier:
    P: 24
    sigma_Mb:
        - 0
        #- 0.3
        #- 1
        #- 3

Kalman:
    win_size:
        - 500_000
    d_win:
        - 250_000