URLs:
    GRCh38:
        gtf: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v43.basic.annotation.gtf.gz"
        genome: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.primary_assembly.genome.fa.gz"
        cdna: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.pc_transcripts.fa.gz"
    GRCm39:
        gtf: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/gencode.vM33.basic.annotation.gtf.gz"
        genome: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/GRCm39.primary_assembly.genome.fa.gz"
        cdna: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/gencode.vM33.pc_transcripts.fa.gz"
    GRCm38:
        gtf: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/gencode.vM23.basic.annotation.gtf.gz"
        genome: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/GRCm38.primary_assembly.genome.fa.gz"
        cdna: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/gencode.vM23.pc_transcripts.fa.gz"


outfold_genome:             "resources/genome"
outfold_fastq:              "resources/fastq"
outfold_fastq_trimmed:      "resources/fastq_trimmed"

Bin_size:
    #- '100'
    - '1000'
    #- '10000'

Samples:
    - CT00
    - CT04
    - CT08
    - CT12
    - CT16
    - CT20
    - CT24
    - CT28
    - CT32
    - CT36
    - CT40
    - CT44

Fastq_Files:
    SE:
        - PRO_SEQ_CT00_S1
        - PRO_SEQ_CT04_S2
        - PRO_SEQ_CT08_S3
        - PRO_SEQ_CT12_S4
        - PRO_SEQ_CT16_S5
        - PRO_SEQ_CT20_S6
        - PRO_SEQ_CT24_S7
        - PRO_SEQ_CT28_S8
        - PRO_SEQ_CT32_S9
        - PRO_SEQ_CT36_S10
        - PRO_SEQ_CT40_S11
        - PRO_SEQ_CT44_S12
    PE:
        - 18035FL-105-01_S1_L005
        - 18035FL-105-01_S1_L006
        - 18035FL-105-01V1-01_S1_L008
        - 18035FL-105-02_S2_L005
        - 18035FL-105-02_S2_L006
        - 18035FL-105-01V1-02_S2_L008
        - 18035FL-105-03_S3_L005
        - 18035FL-105-03_S3_L006
        - 18035FL-105-01V1-03_S3_L008
        - 18035FL-105-04_S4_L005
        - 18035FL-105-04_S4_L006
        - 18035FL-105-01V1-04_S4_L008
        - 18035FL-105-05_S5_L005
        - 18035FL-105-05_S5_L006
        - 18035FL-105-01V1-05_S5_L008
        - 18035FL-105-06_S6_L005
        - 18035FL-105-06_S6_L006
        - 18035FL-105-01V1-06_S6_L008
        - 18035FL-105-07_S7_L005
        - 18035FL-105-07_S7_L006
        - 18035FL-105-01V1-07_S7_L008
        - 18035FL-105-08_S8_L005
        - 18035FL-105-08_S8_L006
        - 18035FL-105-01V1-08_S8_L008
        - 18035FL-105-09_S9_L005
        - 18035FL-105-09_S9_L006
        - 18035FL-105-01V1-09_S9_L008
        - 18035FL-105-10_S10_L005
        - 18035FL-105-10_S10_L006
        - 18035FL-105-01V1-10_S10_L008
        - 18035FL-105-11_S11_L005
        - 18035FL-105-11_S11_L006
        - 18035FL-105-01V1-11_S11_L008
        - 18035FL-105-12_S12_L005
        - 18035FL-105-12_S12_L006
        - 18035FL-105-01V1-12_S12_L008

Reads:
    - R1
    - R2

read_length:
    SE:
        75
    PE:
        151
adapter:
    fwd: TGGAATTCTCGGGTGCCAAGG
    rev: GATCGTCGGACTGTAGAACTCTGAAC
# Adapters from: https://support-docs.illumina.com/SHARE/AdapterSequences/Content/SHARE/AdapterSeq/TruSeq/TruSeqSmallRNA.htm
# Reverse complement of the Illumina TruSeq Small RNA 5' adapter: 'GUUCAGAGUUCUACAGUCCGACGAUC'.translate(''.maketrans('ACGU','TGCA'))[::-1]

MAPQ_min: 10 # Minimum MAPQ score for reads to be considered (Phred-scaled)

mate_dist_max: 1000 # Maximum distance between mates for paired-end reads


Strands:
    - forward
    - reverse
Chromosomes:
    - chr1
    - chr2
    - chr3
    - chr4
    - chr5
    - chr6
    - chr7
    - chr8
    - chr9
    - chr10
    - chr11
    - chr12
    - chr13
    - chr14
    - chr15
    - chr16
    - chr17
    - chr18
    - chr19
    - chrX
    - chrY
    - chrM

Space_Time_Fourier:
    P: 24
    sigma_Mb:
        - 0.1
        - 0.3
        - 1
        #- 3

Kalman:
    win_size:
        - 500_000
    d_win:
        - 250_000

Expressed_regions:
    smooth_window: 1000
    threshold_expressed_regions: 2
    threshold_small_regions: 10_000